/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoedd_vac;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UnsupportedLookAndFeelException;
import com.google.gson.JsonParser;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonPrimitive;
import java.awt.image.BufferedImage;
import java.io.FileWriter;
import java.io.InputStream;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Map.Entry;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author IKAROS
 */
public class Arbol_B extends javax.swing.JFrame implements Runnable {
ArrayList<Integer> datos = new ArrayList<Integer>();
public static String elemento;
public static String eleccion;
public static int count = 0;
public static int contador = 0;
Thread t;
Thread t2;
Thread t3;
ArbolB tree = new ArbolB(2);
ArbolB tree2 = new ArbolB(2);
    /**
     * Creates new form Arbol_B
     */
    public Arbol_B() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ar = new javax.swing.JButton();
        btn_auto = new javax.swing.JButton();
        btn_manual = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        imagen = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        txt_ruta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_ar.setBackground(new java.awt.Color(51, 51, 255));
        btn_ar.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_ar.setText("B Tree");
        btn_ar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arActionPerformed(evt);
            }
        });

        btn_auto.setBackground(new java.awt.Color(51, 51, 255));
        btn_auto.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_auto.setText("Automatico");
        btn_auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_autoActionPerformed(evt);
            }
        });

        btn_manual.setBackground(new java.awt.Color(51, 51, 255));
        btn_manual.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_manual.setText("Manual");
        btn_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualActionPerformed(evt);
            }
        });

        btn_next.setBackground(new java.awt.Color(51, 51, 255));
        btn_next.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_next.setText("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        imagen.setText("jLabel1");
        jScrollPane1.setViewportView(imagen);

        btn_back.setBackground(new java.awt.Color(51, 51, 255));
        btn_back.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_back.setText("<-- Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_manual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_auto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_next)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ar)
                    .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btn_auto)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_manual)
                    .addComponent(btn_next))
                .addContainerGap(323, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_arActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arActionPerformed
        try {
            String ruta=" ";
            JFileChooser jf =  new JFileChooser();
            jf.showOpenDialog(this);
            File archivo = jf.getSelectedFile();
            if(archivo!=null){
            txt_ruta.setText(archivo.getAbsolutePath());
            ruta=txt_ruta.getText();
            }
            Lectura(ruta);
        }catch(IOException ex){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_arActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Menu me = new Menu();
        me.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_autoActionPerformed
        eleccion = "automatico";
        t = new Thread(this,"Hilo 1");
        t.start();
    }//GEN-LAST:event_btn_autoActionPerformed

    private void btn_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualActionPerformed
        eleccion = "manual";
        
    }//GEN-LAST:event_btn_manualActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        t2 = new Thread(this, "hilo2");
        t2.start();
    }//GEN-LAST:event_btn_nextActionPerformed
 
    public void Lectura(String path) throws IOException{
         JsonParser parser = new JsonParser();
         FileReader fr = new FileReader(path);
         JsonElement datos = parser.parse(fr);
         lectJson(datos);
         txt_ruta.setText(" ");
     }
     
     public void lectJson(JsonElement elemento){
         int numeros;
         String paso;
         if(elemento.isJsonObject()){
            System.out.println("es objeto");
            JsonObject obj  = elemento.getAsJsonObject();
            java.util.Set<java.util.Map.Entry<String,JsonElement>> entradas = obj.entrySet();
            java.util.Iterator<java.util.Map.Entry<String,JsonElement>> iter =  entradas.iterator();
            while(iter.hasNext()){
                java.util.Map.Entry<String,JsonElement> entrada = iter.next();
                System.out.println("clave: "+entrada.getKey());
                
                System.out.println("valor: ");
                lectJson(entrada.getValue());
            }
            
         }else
         if(elemento.isJsonArray()){
             JsonArray array = elemento.getAsJsonArray();
             System.out.println("array "+array.size());
             java.util.Iterator<JsonElement> iter = array.iterator();
             while(iter.hasNext()){
                 JsonElement entrada = iter.next();
                 lectJson(entrada);
             }
         }else if(elemento.isJsonPrimitive()){
             System.out.println("es pri");
             JsonPrimitive valor = elemento.getAsJsonPrimitive();
             if(valor.isBoolean()){
                 System.out.println("es boo"+valor.getAsBoolean());
             }else if(valor.isNumber()){
                 //System.out.println("es num "+ valor.getAsNumber());
                 paso = valor.getAsNumber().toString();
                 numeros = Integer.parseInt(paso);
                 datos.add(numeros);
             }else if(valor.isString()){
                 //nombre = valor.getAsString();
                // System.out.print("es texto "+valor.getAsString());
             }
         }else if(elemento.isJsonNull()){
             System.out.println("es null");
         }else{
             System.out.println("es otra cosa");
         }
     }
     
     public void run(){
         if(eleccion.equals("automatico")){
             for(int i=0;i<datos.size();i++){
                 try {
                     tree.insert(new LlaveEntero(datos.get(i)), "Dummy " + i);
                     graficar("ImagenArbolB"+i+".jpg");
                     Thread.sleep(2000);
                     imagen.setIcon(new ImageIcon("ImagenArbolB"+i+".jpg"));
                     imagen.repaint();
                 } catch (InterruptedException ex) {
                     Logger.getLogger(Arbol_B.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
         }else if(eleccion.equals("manual")){
             if(contador==0){
                 try {
                     tree2.insert(new LlaveEntero(datos.get(contador)), "Dummy " + contador);
                     graficar2("ImagenArbolBMa"+contador+".jpg");
                     Thread.sleep(2000);
                     imagen.setIcon(new ImageIcon("ImagenArbolBMa"+contador+".jpg"));
                     imagen.repaint();
                     contador++;
                 } catch (InterruptedException ex) {
                     Logger.getLogger(Arbol_B.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else if(contador>datos.size()){
                 JOptionPane.showMessageDialog(null, "Llego al limite de datos ");
             }else{
                 try {
                     tree2.insert(new LlaveEntero(datos.get(contador)), "Dummy " + contador);
                     graficar2("ImagenArbolBMa"+contador+".jpg");
                     Thread.sleep(2000);
                     imagen.setIcon(new ImageIcon("ImagenArbolBMa"+contador+".jpg"));
                     imagen.repaint();
                     contador++;
                 } catch (InterruptedException ex) {
                     Logger.getLogger(Arbol_B.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
         }
     }
     public void graficar(String path){
         FileWriter f = null;
    try {
        f = new FileWriter( "grafo1.txt");
        f.write(tree.toDot());
        f.close();
    } catch (IOException ex) {
        Logger.getLogger(Arbol_B.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        try {
            f.close();
        } catch (IOException ex) {
            Logger.getLogger(Arbol_B.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    try {

            String dotPath =
                "C:\\Program Files (x86)\\Graphviz2.26.3\\bin\\dot.exe";

            String fileInputPath = "grafo1.txt";
            String fileOutputPath = path;

            String tParam = "-Tjpg";
            String tOParam = "-o";

            String[] cmd = new String[5];
            cmd[0] = dotPath;
            cmd[1] = tParam;
            cmd[2] = fileInputPath;
            cmd[3] = tOParam;
            cmd[4] = fileOutputPath;

            Runtime rt = Runtime.getRuntime();

            rt.exec(cmd);

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
        }
        
        
        try {
            
            
            String[] cmd = new String[4];
            cmd[0] = "cmd";
            cmd[1] = "/C";
            cmd[2] = "start";
            cmd[3] = path;
            
            Runtime rt = Runtime.getRuntime();

            rt.exec(cmd);
            
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }        
    //}
    
    
     }
     public void graficar2(String path){
         FileWriter f = null;
         try {
            f = new FileWriter( "grafo2.txt");
            f.write(tree2.toDot());
            f.close();
        } catch (IOException ex) {
            Logger.getLogger(Arbol_B.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                f.close();
            } catch (IOException ex) {
                Logger.getLogger(Arbol_B.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {

            String dotPath =
                "C:\\Program Files (x86)\\Graphviz2.26.3\\bin\\dot.exe";

            String fileInputPath = "grafo2.txt";
            String fileOutputPath = path;

            String tParam = "-Tjpg";
            String tOParam = "-o";

            String[] cmd = new String[5];
            cmd[0] = dotPath;
            cmd[1] = tParam;
            cmd[2] = fileInputPath;
            cmd[3] = tOParam;
            cmd[4] = fileOutputPath;

            Runtime rt = Runtime.getRuntime();

            rt.exec(cmd);

        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
        }
        
        
        try {
            
            
            String[] cmd = new String[4];
            cmd[0] = "cmd";
            cmd[1] = "/C";
            cmd[2] = "start";
            cmd[3] = path;
            
            Runtime rt = Runtime.getRuntime();

            rt.exec(cmd);
            
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }        
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arbol_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arbol_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arbol_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arbol_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arbol_B().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ar;
    private javax.swing.JButton btn_auto;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_manual;
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_ruta;
    // End of variables declaration//GEN-END:variables
}
