/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoedd_vac;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UnsupportedLookAndFeelException;
import com.google.gson.JsonParser;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonPrimitive;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Map.Entry;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import static proyectoedd_vac.Avl.Node;


/**
 *
 * @author IKAROS
 */
public class LearningAVL extends javax.swing.JFrame implements Runnable {
ArrayList<Integer> datos = new ArrayList<Integer>();
public static int primero;
public static String elemento;
public static String eleccion;
public static int count = 0;
public static int contador = 0;
Thread t;
Thread t2;
Thread t3;
Avl tree = new Avl();
Avl tree2 = new Avl();

    /**
     * Creates new form Learning
     */
    public LearningAVL() {
        initComponents();
        String infor = "fe =altura arbolderecho"+"\n"+"-altura arbolizquiedo";
        lbl_info.setText(infor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_avl = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_auto = new javax.swing.JButton();
        btn_manual = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        txt_eli = new javax.swing.JTextField();
        txt_ruta = new javax.swing.JTextField();
        lbl_ejemplo = new javax.swing.JLabel();
        btn_next = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        lbl_info = new javax.swing.JLabel();
        btn_recorridos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_avl.setBackground(new java.awt.Color(0, 102, 102));
        btn_avl.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_avl.setText("AVL TREE");
        btn_avl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avlActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(0, 102, 102));
        btn_eliminar.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_auto.setBackground(new java.awt.Color(0, 102, 102));
        btn_auto.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_auto.setText("Automatico");
        btn_auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_autoActionPerformed(evt);
            }
        });

        btn_manual.setBackground(new java.awt.Color(0, 102, 102));
        btn_manual.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_manual.setText("Manual");
        btn_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manualActionPerformed(evt);
            }
        });

        lbl_ejemplo.setText("jLabel1");

        btn_next.setBackground(new java.awt.Color(0, 102, 102));
        btn_next.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_next.setText("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(0, 102, 102));
        btn_back.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_back.setText("<--Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        lbl_info.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_info.setText("jLabel1");
        lbl_info.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btn_recorridos.setBackground(new java.awt.Color(0, 102, 102));
        btn_recorridos.setFont(new java.awt.Font("Sitka Text", 3, 12)); // NOI18N
        btn_recorridos.setText("Recorridos");
        btn_recorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recorridosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_manual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_avl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_auto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_next)
                                        .addGap(20, 20, 20))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                            .addComponent(txt_eli))
                                        .addGap(0, 99, Short.MAX_VALUE))))
                            .addComponent(lbl_ejemplo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_back)
                                    .addComponent(lbl_info, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_recorridos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_avl)
                            .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_eliminar)
                            .addComponent(txt_eli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_auto)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_manual)
                            .addComponent(btn_next))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_back)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_info, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_recorridos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ejemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_avlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avlActionPerformed
        try {
            String ruta=" ";
            JFileChooser jf =  new JFileChooser();
            jf.showOpenDialog(this);
            File archivo = jf.getSelectedFile();
            if(archivo!=null){
            txt_ruta.setText(archivo.getAbsolutePath());
            ruta=txt_ruta.getText();
            }
            Lectura(ruta);
        }catch(IOException ex){
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_avlActionPerformed

    private void btn_autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_autoActionPerformed
        eleccion = "automatico";
        t = new Thread(this,"Hilo 1");
        t.start();
        
    }//GEN-LAST:event_btn_autoActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        elemento = txt_eli.getText().replace(" ", "");
        eleccion = "eliminar";
        t2 = new Thread(this, "Hilo 2");
        t2.start();
        /*int num = Integer.parseInt(elemento);
        tree.delete(num);
        tree.root.graficar("ImagenArbolAVLeli.jpg");
        image.setIcon(new ImageIcon("ImagenArbolAVLeli.jpg"));
        image.repaint(); 
        txt_eli.setText(" ");*/
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Menu me = new Menu();
        me.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manualActionPerformed
        eleccion ="manual";
    }//GEN-LAST:event_btn_manualActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        t3 = new Thread(this,"hilo 3");
        t3.start();
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_recorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recorridosActionPerformed
        tree.inorder();
        tree.preorder();
        tree.postorder();
        LearningReco recorri = new LearningReco();
        recorri.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_recorridosActionPerformed
public void Lectura(String path) throws IOException{
         JsonParser parser = new JsonParser();
         FileReader fr = new FileReader(path);
         JsonElement datos = parser.parse(fr);
         lectJson(datos);
         txt_ruta.setText(" ");
     }
     
     public void lectJson(JsonElement elemento){
         int numeros;
         String paso;
         if(elemento.isJsonObject()){
            System.out.println("es objeto");
            JsonObject obj  = elemento.getAsJsonObject();
            java.util.Set<java.util.Map.Entry<String,JsonElement>> entradas = obj.entrySet();
            java.util.Iterator<java.util.Map.Entry<String,JsonElement>> iter =  entradas.iterator();
            while(iter.hasNext()){
                java.util.Map.Entry<String,JsonElement> entrada = iter.next();
                System.out.println("clave: "+entrada.getKey());
                
                System.out.println("valor: ");
                lectJson(entrada.getValue());
            }
            
         }else
         if(elemento.isJsonArray()){
             JsonArray array = elemento.getAsJsonArray();
             System.out.println("array "+array.size());
             java.util.Iterator<JsonElement> iter = array.iterator();
             while(iter.hasNext()){
                 JsonElement entrada = iter.next();
                 lectJson(entrada);
             }
         }else if(elemento.isJsonPrimitive()){
             System.out.println("es pri");
             JsonPrimitive valor = elemento.getAsJsonPrimitive();
             if(valor.isBoolean()){
                 System.out.println("es boo"+valor.getAsBoolean());
             }else if(valor.isNumber()){
                 //System.out.println("es num "+ valor.getAsNumber());
                 paso = valor.getAsNumber().toString();
                 numeros = Integer.parseInt(paso);
                 datos.add(numeros);
             }else if(valor.isString()){
                 //nombre = valor.getAsString();
                // System.out.print("es texto "+valor.getAsString());
             }
         }else if(elemento.isJsonNull()){
             System.out.println("es null");
         }else{
             System.out.println("es otra cosa");
         }
     }
     
    
     
     public void run(){
         if(eleccion.equals("eliminar")){
             
             System.out.println("eliminio");
             try {
                 int num = Integer.parseInt(elemento);
                 tree.delete(num);
                 count++;
                 tree.root.graficar("ImagenArbolAVLeli"+count+".jpg");
                 Thread.sleep(2000);
                 //image.updateUI();
                 image.setIcon(new ImageIcon("ImagenArbolAVLeli"+count+".jpg"));
                 image.repaint();
                 txt_eli.setText(" ");
             } catch (InterruptedException ex) {
                 Logger.getLogger(LearningAVL.class.getName()).log(Level.SEVERE, null, ex);
             }
         }else if(eleccion.equals("automatico")){
             
         
         try{
         for(int i=0;i<datos.size();i++){
             if(i==0){
                tree.insert(datos.get(i));
                tree.root.graficar("ImagenArbolAVL"+i+".jpg");
                Thread.sleep(2000);
                image.setIcon(new ImageIcon("ImagenArbolAVL"+i+".jpg"));
                image.repaint();
             }else{
                 if(i==(datos.size()-1)){
                    System.out.println(datos.size()-1);
                    tree.insert(datos.get(i));
                    tree.root.graficar("ImagenArbolAVL"+i+".jpg");
                    Thread.sleep(2000);
                    image.setIcon(new ImageIcon("ImagenArbolAVL"+i+".jpg"));
                    image.repaint(); 
              }else{
                    primero = datos.get(i);
                    tree.root.graficar("ImagenArbolAVL"+i+".jpg");
                    Thread.sleep(2000);
                    image.setIcon(new ImageIcon("ImagenArbolAVL"+i+".jpg"));
                    image.repaint(); 
                    tree.insert(datos.get(i)); 
                 }
                
             }
             
                
                 //pintar();
                System.out.println(datos.get(i));
                Thread.sleep(5000);
         }
         }catch(InterruptedException e){
             
         }
         }else if(eleccion.equals("manual")){
             if(contador==0){
                 try {
                     tree2.insert(datos.get(contador));
                     tree2.root.graficar("ImagenArbolAVLMa"+contador+".jpg");
                     Thread.sleep(2000);
                     image.setIcon(new ImageIcon("ImagenArbolAVLMa"+contador+".jpg"));
                     image.repaint();
                     contador++;
                 } catch (InterruptedException ex) {
                     Logger.getLogger(LearningAVL.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else if(contador==(datos.size()-1)){
                 try {
                     System.out.println(datos.size()-1);
                     tree2.insert(datos.get(contador));
                     tree2.root.graficar("ImagenArbolAVLMa"+contador+".jpg");
                     Thread.sleep(2000);
                     image.setIcon(new ImageIcon("ImagenArbolAVLMa"+contador+".jpg")); 
                     image.repaint();
                 } catch (InterruptedException ex) {
                     Logger.getLogger(LearningAVL.class.getName()).log(Level.SEVERE, null, ex);
                 }
              }else if(contador > (datos.size()-1)){
                  JOptionPane.showMessageDialog(null, "Llego al limite de datos ");
              }else{
                 try {
                     primero = datos.get(contador);
                     tree2.root.graficar("ImagenArbolAVLMa"+contador+".jpg");
                     Thread.sleep(2000);
                     image.setIcon(new ImageIcon("ImagenArbolAVLMa"+contador+".jpg"));
                     image.repaint();
                     tree2.insert(datos.get(contador));
                     contador++;
                 } catch (InterruptedException ex) {
                     Logger.getLogger(LearningAVL.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 }
                 
             
         }
         tree.root.graficar("ImagenArbolAVl.jpg");
     
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningAVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningAVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningAVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningAVL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearningAVL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_auto;
    private javax.swing.JButton btn_avl;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_manual;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_recorridos;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ejemplo;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JTextField txt_eli;
    private javax.swing.JTextField txt_ruta;
    // End of variables declaration//GEN-END:variables
}
