
package proyectoedd_vac;

import javax.swing.JOptionPane;
//import  static proyectoedd_vac.Login.name;
//import  static proyectoedd_vac.Login.pass;
/**
 *
 * @author IKAROS
 */
public class Menu extends javax.swing.JFrame {
Login log = new Login();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        lbl_info.setText("Nombre: "+log.name+" Carnet: "+log.pass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_avl = new javax.swing.JButton();
        btn_treeb = new javax.swing.JButton();
        btn_grafo = new javax.swing.JButton();
        btn_orden = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        lbl_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_avl.setBackground(new java.awt.Color(102, 102, 255));
        btn_avl.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btn_avl.setText("Tree AVL");
        btn_avl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avlActionPerformed(evt);
            }
        });

        btn_treeb.setBackground(new java.awt.Color(102, 102, 255));
        btn_treeb.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btn_treeb.setText("Tree B");
        btn_treeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_treebActionPerformed(evt);
            }
        });

        btn_grafo.setBackground(new java.awt.Color(102, 102, 255));
        btn_grafo.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btn_grafo.setText("Grafo");

        btn_orden.setBackground(new java.awt.Color(102, 102, 255));
        btn_orden.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btn_orden.setText("Ordenamientos");
        btn_orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(102, 102, 255));
        btn_back.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        btn_back.setText("<--Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_avl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_grafo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_orden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_treeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addGap(18, 18, 18)
                .addComponent(lbl_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back)
                    .addComponent(lbl_info))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_avl)
                    .addComponent(btn_treeb))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_grafo)
                    .addComponent(btn_orden))
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_avlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avlActionPerformed
        LearningAVL avl = new LearningAVL();
        avl.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_avlActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Login log = new Login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_treebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_treebActionPerformed
        Arbol_B b = new Arbol_B();
        b.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_treebActionPerformed

    private void btn_ordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenActionPerformed
        int opcion = 0;
        String op;
        op = JOptionPane.showInputDialog("Seleccione una opcion: \n"
        + " 1. -Ordenamiento Burbuja\n"
        + " 2. -Ordenamiento por Insercion\n"
        + " 3. -Ordenamiento por Quicksort");
        if(op!=null){
            opcion = Integer.parseInt(op);
            switch(opcion){
            case 1:
                OrdenamientoBurbu burbuja = new OrdenamientoBurbu();
                burbuja.setVisible(true);
                setVisible(false);
                break;
            case 2:
                OrdenamientoInsercion insercion = new OrdenamientoInsercion();
                insercion.setVisible(true);
                setVisible(false);
                break;
            case 3:
                OrdenamientoQuick quick = new OrdenamientoQuick();
                quick.setVisible(true);
                setVisible(false);
                break;
            }
        }
            
    }//GEN-LAST:event_btn_ordenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_avl;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_grafo;
    private javax.swing.JButton btn_orden;
    private javax.swing.JButton btn_treeb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_info;
    // End of variables declaration//GEN-END:variables
}
